/*
 * generated by Xtext 2.15.0
 */
package edu.uoc.som.jarvis.language.common.tests

import com.google.inject.Inject
import edu.uoc.som.jarvis.language.common.common.PropertyAccess
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CommonInjectorProvider)
class CommonParsingTest {
	@Inject
	ParseHelper<PropertyAccess> parseHelper
	
	@Test
	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assertions.assertNotNull(result)
//		val errors = result.eResource.errors
//		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
