/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModuleStandaloneSetup extends ModuleStandaloneSetupGenerated {

	def static void doSetup() {
		new ModuleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
