/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.execution.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ExecutionScopeProvider extends AbstractExecutionScopeProvider {

}
