/*
 * generated by Xtext 2.12.0
 */
package com.xatkit.language.execution.tests

import com.google.inject.Inject
import com.xatkit.execution.ExecutionModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ExecutionInjectorProvider)
class ExecutionParsingTest {
	@Inject
	ParseHelper<ExecutionModel> parseHelper
	
	@Test
	def void loadModel() {
		/*
		 * This test case fails by trying to load a resource with the URI classpath:/com/xatkit/language/Module
		 .xmi
		 * that does not exist (see https://github.com/xatkit-bot-platform/xatkit/issues/14)
		 */
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
