/*
 * generated by Xtext 2.15.0
 */
package edu.uoc.som.jarvis.language.common


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CommonRuntimeModule extends AbstractCommonRuntimeModule {
}
