/*
 * generated by Xtext 2.15.0
 */
package edu.uoc.som.jarvis.language.common.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CommonUiModule extends AbstractCommonUiModule {
}
