/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.validation

import fr.zelus.jarvis.orchestration.OrchestrationModel
import org.eclipse.xtext.validation.Check
import fr.zelus.jarvis.language.util.ModuleRegistry
import java.io.IOException
import fr.zelus.jarvis.orchestration.OrchestrationPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class OrchestrationValidator extends AbstractOrchestrationValidator {
	
	@Check
	def checkOrchestrationModelValidImports(OrchestrationModel model) {
		model.imports.forEach[i | 
			println("Checking import " + i)
			try {
				/*
				 * Remove the quotes at the beginning and at the end of the import string
				 */
				ModuleRegistry.instance.loadModule(i)
			} catch(IOException e) {
				println("Import checking failed")
				e.printStackTrace
				error('Module ' + i + "does not exist", OrchestrationPackage.Literals.ORCHESTRATION_MODEL__IMPORTS)
			}
		]
	}
}
