/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.ide


/**
 * Use this class to register ide components.
 */
class OrchestrationIdeModule extends AbstractOrchestrationIdeModule {
}
