/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.tests

import com.google.inject.Inject
import fr.zelus.jarvis.module.Module
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl
import org.eclipse.emf.common.util.URI
import java.util.Collections

@RunWith(XtextRunner)
@InjectWith(ModuleInjectorProvider)
class ModuleParsingTest {
	@Inject
	ParseHelper<Module> parseHelper
	
	@Test
	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
