/*
 * generated by Xtext 2.12.0
 */
package edu.uoc.som.jarvis.language.platform


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PlatformStandaloneSetup extends PlatformStandaloneSetupGenerated {

	def static void doSetup() {
		new PlatformStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
