/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OrchestrationStandaloneSetup extends OrchestrationStandaloneSetupGenerated {

	def static void doSetup() {
		new OrchestrationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
