/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.platform.ide


/**
 * Use this class to register ide components.
 */
class PlatformIdeModule extends AbstractPlatformIdeModule {
}
