/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.tests

import com.google.inject.Inject
import fr.zelus.jarvis.orchestration.OrchestrationModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OrchestrationInjectorProvider)
class OrchestrationParsingTest {
	@Inject
	ParseHelper<OrchestrationModel> parseHelper
	
	@Test
	def void loadModel() {
		/*
		 * This test case fails by trying to load a resource with the URI classpath:/fr/zelus/jarvis/language/Module.xmi 
		 * that does not exist (see https://github.com/gdaniel/jarvis/issues/14)
		 */
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
