/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.execution.ide


/**
 * Use this class to register ide components.
 */
class ExecutionIdeModule extends AbstractExecutionIdeModule {
}
