/*
 * generated by Xtext 2.12.0
 */
package fr.zelus.jarvis.language.intent


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IntentRuntimeModule extends AbstractIntentRuntimeModule {
}
